/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Valentine {
  'color' : string,
  'text' : string,
  'photoSrc' : [] | [ExternalBlob],
}
export interface ValentineSnapshot {
  'writeTokenHash' : string,
  'saveId' : string,
  'createdBy' : Principal,
  'valentine' : Valentine,
  'version' : bigint,
  'lastUpdateTimestamp' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllValentineSnapshots' : ActorMethod<[], undefined>,
  'createValentineSnapshot' : ActorMethod<[Valentine], [string, string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGlobalLatest' : ActorMethod<[], [] | [ValentineSnapshot]>,
  'getGlobalLatestVersion' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getValentineSnapshot' : ActorMethod<[string], [] | [ValentineSnapshot]>,
  'getValentineSnapshotVersion' : ActorMethod<[string], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listValentineSnapshots' : ActorMethod<[bigint], Array<ValentineSnapshot>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGlobalLatest' : ActorMethod<[Valentine], bigint>,
  'updateValentineSnapshot' : ActorMethod<
    [string, bigint, Valentine, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];